### PR TITLE
Build for Nerd Fonts v3 (a breaking change)

### PR DESCRIPTION
**Pull request by hjdarnel**
[Nerd Fonts recently released a v3](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) which is causing plugins that use a Nerd Font to upgrade. Unfortunately this means if you don't have an updated v3 Nerd Font, stuff starts breaking ([like here](https://github.com/onsails/lspkind.nvim/pull/64#issuecomment-1550470438)).

I removed the now unnecessary `--also-windows` flag from the build script, as both fonts should now be Windows compatible ([see here for that change](https://github.com/ryanoasis/nerd-fonts/pull/1028)). I also rebuilt the font and validated that it works correctly after installing.

### CODE REVIEW

**Comment by hjdarnel** [comment]
@Karmenzind tagging you in case you weren't notified

**Comment by Karmenzind** [comment]
sorry for the late
I will check and merge it soon

**Comment by Karmenzind** [comment]
@hjdarnel Thanks for your work!
I want to know what original font file are you using? https://www.fontmirror.com/monaco or another one? Please give me the source link.

**Comment by hjdarnel** [comment]
@Karmenzind I pulled it from my system fonts (on macOS) so fontmirror.com should be a good link to it.

**Comment by Karmenzind** [comment]
@hjdarnel thanks :)

**Pull request merged**
